CREATE TABLE IF NOT EXISTS RecordsProducts
(
    recordproduct_id int(11) NOT NULL AUTO_INCREMENT,
 
    record_id INT,
    product_id INT,
    INDEX(record_id),
    INDEX(product_id),
 
    PRIMARY KEY (recordproduct_id),
    FOREIGN KEY (record_id) REFERENCES Records (record_id),
    FOREIGN KEY (product_id) REFERENCES ProductsList (product_id)
);

# 회원
CREATE TABLE CUST_BAS(CUST_ID INT(20) NOT NULL AUTO_INCREMENT, ENAME VARCHAR(255) NOT NULL, ID VARCHAR(255) NOT NULL, PWD VARCHAR(255) NOT NULL,
PHONE VARCHAR(255) NOT NULL, EMAIL VARCHAR(255) NOT NULL, PRIMARY KEY(CUST_ID));

# 회원 상세정보
CREATE TABLE CUST_DT(CUST_ID INT(20) NOT NULL AUTO_INCREMENT, PAY_SYS VARCHAR(255) NOT NULL, MBS VARCHAR(255) NOT NULL DEFAULT '화이트', POINT INT NOT NULL DEFAULT 50000, DATA_SIZE DOUBLE NOT NULL DEFAULT 0,
PRIMARY KEY (CUST_ID), FOREIGN KEY(CUST_ID) REFERENCES CUST_BAS(CUST_ID));

# 이벤트
CREATE TABLE EVT_EVT(EVT_ID INT(20) NOT NULL AUTO_INCREMENT, EVT_NM VARCHAR(255) NOT NULL, EVT_DT VARCHAR(255) NOT NULL,
ST_DATE DATE NOT NULL, END_DATE DATE NOT NULL, EVT_ST INT NOT NULL DEFAULT 0, EVT_FILE_URL VARCHAR(255) NOT NULL, EVT_CTG VARCHAR(255) NOT NULL,
PRIMARY KEY (EVT_ID));

# 응모자
CREATE TABLE CUST_APP_RES(APP_ID INT(20) NOT NULL AUTO_INCREMENT, EVT_ID INT, CUST_ID INT,
PRIZE INT NOT NULL DEFAULT 0,
PRIMARY KEY (APP_ID),
FOREIGN KEY(EVT_ID) REFERENCES EVT_EVT(EVT_ID),
FOREIGN KEY(CUST_ID) REFERENCES CUST_DT(CUST_ID));

# 검색
SELECT * FROM APPLIC;

# 순서대로 삭제
DROP TABLE CUSTOMER;
DROP TABLE CUST_BAS;
DROP TABLE EVENT;
DROP TABLE APPLICATION;


ALTER TABLE customer 





